---
title: "Chapter 14 and 15 HW"
author: "Kyle Ligon"
date: "March 30, 2018"
output:
  pdf_document: default
  html_document: default
---
14.8 (a) Assess ANOVA assumptions using the graph from PROC MIXED.

```{r, warning = FALSE, echo = FALSE, message = FALSE}
library(tidyverse)
library(grid)
library(gridExtra)
library(kableExtra)
library(multcomp)
a1_p1 <- data.frame(matrix(c(rep("a1", 10), rep("p1", 10), 19, 36, 40, 30, 4, 10, 30, 5, 34, 21), ncol = 3, nrow = 10))
a2_p1 <- data.frame(matrix(c(rep("a2", 10), rep("p1", 10), 19, 35, 22, 28, 1, 27, 27, 16, 3, 18), ncol = 3, nrow = 10))
a3_p1 <- data.frame(matrix(c(rep("a3", 10), rep("p1", 10), 37, 6, 28, 4, 32, 16, 8, 41, 29, 18), ncol = 3, nrow = 10))
a1_p2 <- data.frame(matrix(c(rep("a1", 10), rep("p2", 10), 39, 18, 32, 22, 16, 2, 36, 43, 7, 16), ncol = 3, nrow = 10))
a2_p2 <- data.frame(matrix(c(rep("a2", 10), rep("p2", 10), 30, 47, 6, 27, 44, 26, 33, 48, 23, 21), ncol = 3, nrow = 10))
a3_p2 <- data.frame(matrix(c(rep("a3", 10), rep("p2", 10), 51, 52, 43, 48, 39, 33, 56, 43, 40, 51), ncol = , nrow = 10))
frame <- rbind(a1_p1, a2_p1, a3_p1, a1_p2, a2_p2, a3_p2)
colnames(frame) <- c("ageGroup", "products", "att_spans")
frame$att_spans <- as.numeric(frame$att_spans)
anova_mod <- aov(att_spans ~ ageGroup * products, data = frame)
y <- quantile(anova_mod$residuals[!is.na(anova_mod$residuals)], c(0.25, 0.75))
x <- qnorm(c(0.25, 0.75))
slope = diff(y)/diff(x)
int <- y[1L] - slope*x[1L]


norm_res <- ggplot(data = anova_mod, aes(x = anova_mod$residuals)) + geom_histogram(bins = 6) + xlab("Residuals") + ggtitle("Residuals")


resid_jitter <- ggplot(data = anova_mod, aes(x = anova_mod$fitted.values, y = anova_mod$residuals)) + geom_jitter() +  xlab("Group Mean") + ylab("Residuals") + ggtitle("Residuals vs. Predicted Mean")


qq <- ggplot(data = anova_mod) + stat_qq(aes(sample = anova_mod$residuals), alpha = 0.5) + 
    geom_abline(slope = slope, intercept = int, color = "blue") + ggtitle("Q-Q Plot")


res_sum <- as.table(summary(anova_mod$residuals), nrow= 2, ncol = 6)
grid.arrange(resid_jitter, norm_res, qq, nrow = 2, ncol = 2)
```

14.8 (b) Perform an ANOVA to determine if there is an interaction between the age group and types of products;

```{r, echo = FALSE, messsage = FALSE, warning = FALSE}
#INteraction Term
qf(0.95, 2, 54)
#Age Group
qf(0.95, 2, 56)
#Products
qf(0.95, 1, 56)

anova_mod_noI <- aov(data = frame, formula = att_spans ~ ageGroup + products)
```


