---
title: "Chapter 7 Homework"
author: "Kyle Ligon"
date: "February 17, 2018"
output: pdf_document
---

Problem 7.7 b)
```{r}
#T_U
qchisq((1-0.05)/2, 149)
#T_L
qchisq(0.05/2, 149)
#Lower End
(149)*(9.537^2)/(147.2568)
#Upper End
(149)*(9.537^2)/(117.098)
```

Problem 7.7 c)
```{r}
#chisquare value
(149*9.537^2)/(9^2)
#upper val in Chi Sq test
qchisq(0.99, 149)
#probability in the right tail of our chi-sq dist
1-pchisq(167.3111, 149)
```

Problem 7.16 a) and b)
```{r}
f <- (53.77^2)/(36.94^2)
sqrt((1.58*f))
sqrt((1/1.58)*f)
# part b test stat
f
# part b p-value
1- pf(2.1188, 90, 90)
```

7.16 c) Satterwhaite's Approximation
```{r}
kk <- (53.77^2)/(91)
kk
jj <- (36.94^2)/(91)
jj
kk^2/90 
jj^2/90
31.7716+14.9952
11.2159+2.4984
46.7668/13.7143
```

7.16 d) p-value
```{r}
pt(-0.4284, df = 3)
```

7.18 BFL test for Wild Ranch and Zoo group
```{r, message = F}
library(lawstat)
library(reshape2)
library(tidyverse)
wild <- c(114.7, 128.9, 111.5, 116.4, 134.5, 126.7, 120.6, 129.59)
ranch <- c(120.4, 91.0, 119.6, 119.4, 150.0, 169.7, 100.9, 76.1)
zoo <- c(103.1, 90.7, 129.5, 75.8, 182.5, 76.8, 87.3, 77.3)
weight_m <- matrix(c(wild, ranch, zoo), nrow = 8, ncol = 3, byrow = F)
weight <- data.frame(weight_m)
colnames(weight) <- c("wild", "ranch", "zoo")
weight <- melt(weight)
levene.test(y = weight$value, group = weight$variable, location = "median")
```










